classes:
- system.docker
parameters:
  _param:
    docker_image_gitlab: gitlab/gitlab-ce:10.8.7-ce.0
    gitlab_external_url: http://localhost:11080
    gitlab_port_http: 11080
    gitlab_port_https: 11443
    gitlab_port_ssh: 11022
    gitlab_ssl_cert_path: /etc/gitlab_certs/gitlab.crt
    gitlab_ssl_key_path: /etc/gitlab_certs/gitlab.key
    gitlab_smtp_hostname: localhost
    gitlab_smtp_port: 25
    gitlab_smtp_username: gitlab
    gitlab_smtp_password: gitlab
    gitlab_smtp_domain: localhost
    gitlab_smtp_auth: login
    gitlab_smtp_starttls_auto: "true"
    gitlab_smtp_tls: "true"

    # Default gitlab config
    gitlab_config_default: external_url "${_param:gitlab_external_url}"; nginx["listen_port"] = 80;
    
    # Gitlab config to use SSL
    gitlab_config_ssl: external_url "${_param:gitlab_external_url}"; nginx["listen_port"] = 443; nginx["ssl_certificate"] = "${_param:gitlab_ssl_cert_path}"; nginx["ssl_certificate_key"] = "${_param:gitlab_ssl_key_path}"; nginx["redirect_http_to_https"] = true;
    
    # Use this config when gitlab is behing SSL proxy
    gitlab_config_ssl_proxy: external_url "${_param:gitlab_external_url}"; nginx["listen_port"] = 80; nginx["listen_https"] = false; nginx["proxy_set_headers"] = { "X-Forwarded-Proto" => "https", "X-Forwarded-Ssl" => "on" };

    # Smtp config
    gitlab_config_smtp_default: gitlab_rails["smtp_enable"] = true; gitlab_rails["smtp_address"] = "${_param:gitlab_smtp_hostname}"; gitlab_rails["smtp_port"] = ${_param:gitlab_smtp_port};
    gitlab_config_smtp_auth: gitlab_rails["smtp_enable"] = true; gitlab_rails["smtp_address"] = "${_param:gitlab_smtp_hostname}"; gitlab_rails["smtp_port"] = ${_param:gitlab_smtp_port}; gitlab_rails["smtp_user_name"] = "${_param:gitlab_smtp_username}"; gitlab_rails["smtp_password"] = "${_param:gitlab_smtp_password}"; gitlab_rails["smtp_domain"] = "${_param:gitlab_smtp_domain}"; gitlab_rails["smtp_authentication"] = "${_param:gitlab_smtp_auth}"; gitlab_rails["smtp_enable_starttls_auto"] = ${_param:gitlab_smtp_starttls_auto}; gitlab_rails["smtp_tls"] = ${_param:gitlab_smtp_tls};

  docker:
    client:
      stack:
        gitlab:
          service:
            master:
              image: ${_param:docker_image_gitlab}
              environment:
                GITLAB_OMNIBUS_CONFIG: ${_param:gitlab_config_default} ${_param:gitlab_config_smtp_default}
              deploy:
                restart_policy:
                  condition: any
              ports:
                - "${_param:gitlab_port_http}:80"
                - "${_param:gitlab_port_https}:443"
                - "${_param:gitlab_port_ssh}:22"
              volumes:
                - /srv/volumes/gitlab/config:/etc/gitlab
                - /srv/volumes/gitlab/data:/var/opt/gitlab
                - /srv/volumes/gitlab/logs:/var/log/gitlab
                - /srv/volumes/gitlab/certs:/etc/gitlab_certs
